### PR TITLE
Update astronomical_calendar.py

### PR DESCRIPTION
**Pull request by plonibarploni**
fix for: AttributeError: module 'dateutil.tz' has no attribute 'UTC'

### CODE REVIEW

**Comment by pinnymz** [comment]
@plonibarploni thanks for the PR.  What version of python-dateutil are you targeting?  The version I'm using (2.7.3) doesn't give me this error.  Unit tests all passing...

**Comment by plonibarploni** [comment]
I'm using 3.7. The [pypi page](https://pypi.org/project/zmanim/) says it requires Python >=3.6

**Comment by plonibarploni** [comment]
Indeed, I just updated to 2.7.3, and it doesn't give me this error either. But using `tzutc()` works on both.

**Comment by pinnymz** [comment]
Well then, it makes sense to make this change for better backward compatibility.  Fixed with https://github.com/pinnymz/python-zmanim/commit/54e3bb14693a517664f9ec294803292135016904

**Pull request closed without merging**
